CrowdFunding/Models/Investment.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CrowdFunding.Models
{
    public class Investment
    {
        public Investment()
        {
            IsApproved = false;
        }
        public int Id { get; set; }

        [Display(Name = "Registration number")]
        public string InvestmentRegNo { get; set; }

        public double Amount { get; set; }

        [Display(Name ="Project name")]
        public int ProjectId { get; set; }

        [Display(Name = "Investment type")]
        public int InvestmentTypeId { get; set; }

        [Display(Name = "Investor name")]
        public string InvestorId { get; set; }

        [Display(Name = "Is approved")]
        public bool IsApproved { get; set; }

        [ForeignKey("ProjectId")]
        public Project Project { get; set; }

        [ForeignKey("InvestmentTypeId")]
        public InvestmentType InvestmentType { get; set; }

        [ForeignKey("InvestorId")]
        public Investor Investor { get; set; }


    }
}

CrowdFunding/Models/InvestmentType.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CrowdFunding.Models
{
    public class InvestmentType
    {
        public int Id { get; set; }

        public string Type { get; set; }

        [Display(Name = "Short description")]
        public string ShortDescription { get; set; }

        [Display(Name = "Project id")]
        public int ProjectId { get; set; }

        [ForeignKey("ProjectId")]
        public Project Project { get; set; }

        public List<Investment> Investments { get; set; }
    }
}

CrowdFunding/ViewModels/InvestmentViewModel.cs
using CrowdFunding.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrowdFunding.ViewModels
{
    public class InvestmentViewModel
    {
        public Project Project { get; set; }
        public Investment Investment { get; set; }
        public List<InvestmentType> InvestmentTypes { get; set; }
    }
}

CrowdFunding/Controllers/InvestmentsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CrowdFunding.Data;
using CrowdFunding.Models;
using CrowdFunding.ViewModels;
using Microsoft.AspNetCore.Identity;
using CrowdFunding.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using System.Text.Encodings.Web;

namespace CrowdFunding.Controllers
{
    [Authorize]
    public class InvestmentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ICustomizedId _customizedId;
        private readonly IGetProjectOwner _getProjectOwner;
        private readonly IEmailSender _emailSender;

        public InvestmentsController(ApplicationDbContext context,
                                    UserManager<ApplicationUser> userManager,
                                    ICustomizedId customizedId,
                                    IGetProjectOwner getProjectOwner,
                                    IEmailSender emailSender)
        {
            _context = context;
            _userManager = userManager;
            _customizedId = customizedId;
            _getProjectOwner = getProjectOwner;
            _emailSender = emailSender;
        }

        // GET: Investments
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Investments.Include(i => i.InvestmentType).Include(i => i.Investor).Include(i => i.Project);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Investments/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var investment = await _context.Investments
                .Include(i => i.InvestmentType)
                .Include(i => i.Investor)
                .Include(i => i.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (investment == null)
            {
                return NotFound();
            }

            return View(investment);
        }

        // GET: Investments/Create
        [Authorize(Roles = "Investor")]
        public async Task<IActionResult> Create(int id)
        {
            var project = await _context.Projects.FindAsync(id);
            var investmentTypes = await _context.investmentTypes.Where(x => x.ProjectId == id).ToListAsync();

            var investmentViewModel = new InvestmentViewModel
            {
                Project = project,
                InvestmentTypes = investmentTypes
                
            };

            return View(investmentViewModel);
        }

        // POST: Investments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Investor")]
        public async Task<IActionResult> Create(InvestmentViewModel model)
        {
            var user = await _userManager.GetUserAsync(User);
            var investment = new Investment
            {
                Amount = model.Investment.Amount,
                InvestmentTypeId = model.Investment.InvestmentTypeId,
                ProjectId = model.Project.Id,
                InvestorId = user.Id
            };
            string regNo = _customizedId.InvestmentRegNo(model, user.Id);
            investment.InvestmentRegNo = regNo;

            _context.Investments.Add(investment);
            await _context.SaveChangesAsync();

            var owner = _getProjectOwner.GetOwner(investment.ProjectId);
            var callbackUrl = Url.Page(
                            "/Projects/Details",
                            pageHandler: null,
                            values: new { id = model.Project.Id },
                            protocol: Request.Scheme);

            await _emailSender.SendEmailAsync(owner.Email, model.Project.Name,
                $"{user.Email} pledge {model.Investment.Amount} taka to {model.Project.Name}. Please contact with admin for more details. To see your project <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>");

            return RedirectToAction(nameof(ConfirmPayment));
        }

        // GET: Investments/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var investment = await _context.Investments.FindAsync(id);
            if (investment == null)
            {
                return NotFound();
            }
            ViewData["InvestmentTypeId"] = new SelectList(_context.investmentTypes, "Id", "Id", investment.InvestmentTypeId);
            ViewData["InvestorId"] = new SelectList(_context.Investors, "Id", "Id", investment.InvestorId);
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Name", investment.ProjectId);
            return View(investment);
        }

        // POST: Investments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,InvestmentRegNo,Amount,ProjectId,InvestmentTypeId,InvestorId")] Investment investment)
        {
            if (id != investment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(investment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InvestmentExists(investment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["InvestmentTypeId"] = new SelectList(_context.investmentTypes, "Id", "Id", investment.InvestmentTypeId);
            ViewData["InvestorId"] = new SelectList(_context.Investors, "Id", "Id", investment.InvestorId);
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Name", investment.ProjectId);
            return View(investment);
        }

        // GET: Investments/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var investment = await _context.Investments
                .Include(i => i.InvestmentType)
                .Include(i => i.Investor)
                .Include(i => i.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (investment == null)
            {
                return NotFound();
            }

            return View(investment);
        }

        // POST: Investments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var investment = await _context.Investments.FindAsync(id);
            _context.Investments.Remove(investment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Investor")]
        public IActionResult ConfirmPayment()
        {
            ViewData["BKashNumber"] = "8801717745808";
            return View();
        }

        private bool InvestmentExists(int id)
        {
            return _context.Investments.Any(e => e.Id == id);
        }
    }
}

CrowdFunding/Views/Investments/ConfirmPayment.cshtml
@{
    ViewData["Title"] = "ConfirmPayment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="bkash-payment">
    <h2>Request send to Admin. Please contact Admin with Transaction Id</h2>
    <h1>BKash no. - 01717745808 </h1>
    <h2>Or scan this QR to get number.</h2>
    <qrcode content="@ViewBag.BkashNumber" alt="qrcode" height="200px" width="200px"></qrcode>
</div>

CrowdFunding/Views/Investments/Create.cshtml
@model InvestmentViewModel
@{
    ViewData["Title"] = "Create";

}

<div class="investment">
    <div class="investment-header">
        <a href="/Projects/Details/@Model.Project.Id"><h1>@Model.Project.Name</h1></a>
    </div>
    <div class="investment-main group">
        <div class="investment-body">
            <h3>Support this project</h3>
            <hr />

            @if (!(Model.InvestmentTypes.Count == 0))
            {
                @foreach (var item in Model.InvestmentTypes)
                {
                    <div class="investment-body-item ">
                        <div class="investment-body-item-1">
                            <div class="investment-body-item-p">@item.Type</div>
                            <div class="investment-body-item-p" style="font-weight:300">@item.ShortDescription</div>
                        </div>

                        <form id="investForm" asp-controller="Investments" asp-action="Create" method="post">
                            <input asp-for="Investment.InvestmentTypeId"  type="number" value="@item.Id" hidden />
                            <input asp-for="Project.Id" type="number" value="@Model.Project.Id" hidden />
                            <input asp-for="Project.Name" type="text" value="@Model.Project.Name" hidden />
                            <div class="investment-body-item-div">
                                <input asp-for="Investment.Amount" type="number" placeholder="@item.Type" class="investment-body-item-amount" /> 
                                <input class="investment-body-item-continue" type="submit" value="Continue" />
                            </div>
                        </form>
                    </div>
                }
            }
            else
            {
                <h2>No rewards set yet.</h2>
            }


        </div>
        <div class="investment-side">
            <h1>Our platform is not a store.</h1>
            <h3>It's a way to bring creative projects to life.</h3>
            <p>
                It does not guarantee projects or investigate a creator's ability to complete their project. It is the responsibility of the project creator to complete their project as promised, and the claims of this project are theirs alone.
            </p>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CrowdFunding/Views/Investments/Delete.cshtml
@model CrowdFunding.Models.Investment

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Investment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.InvestmentRegNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.InvestmentRegNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Project.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.InvestmentType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.InvestmentType.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Investor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Investor.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CrowdFunding/Views/Investments/Details.cshtml
@model CrowdFunding.Models.Investment

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Investment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.InvestmentRegNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.InvestmentRegNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Project.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.InvestmentType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.InvestmentType.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Investor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Investor.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CrowdFunding/Views/Investments/Edit.cshtml
@model CrowdFunding.Models.Investment

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Investment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="InvestmentRegNo" class="control-label"></label>
                <input asp-for="InvestmentRegNo" class="form-control" />
                <span asp-validation-for="InvestmentRegNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectId" class="control-label"></label>
                <select asp-for="ProjectId" class="form-control" asp-items="ViewBag.ProjectId"></select>
                <span asp-validation-for="ProjectId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InvestmentTypeId" class="control-label"></label>
                <select asp-for="InvestmentTypeId" class="form-control" asp-items="ViewBag.InvestmentTypeId"></select>
                <span asp-validation-for="InvestmentTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InvestorId" class="control-label"></label>
                <select asp-for="InvestorId" class="form-control" asp-items="ViewBag.InvestorId"></select>
                <span asp-validation-for="InvestorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CrowdFunding/Views/Investments/Index.cshtml
@model IEnumerable<CrowdFunding.Models.Investment>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.InvestmentRegNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Project)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InvestmentType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Investor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.InvestmentRegNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InvestmentType.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Investor.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>